# Bridges — WhatsApp, Instagram and Discord, all from the mautrix project.
#
# Beeper does not publish per-network bridge forks any more: it develops the
# bridges upstream in the `mautrix/*` repos (its own org keeps library forks
# like `beeper/discordgo`), and `bridge-manager`/`bbctl` refuses to talk to
# anything but beeper.com — see the migration section of
# ~/nix-migration/10-matrix-on-warden.md. So these are the same binaries Beeper
# runs, wired to our own Synapse:
#
#   whatsapp   services.mautrix-whatsapp  (nixpkgs module)   port 29318
#   instagram  mautrix-instagram         (hand-written unit) port 29320
#   discord    services.mautrix-discord  (nixpkgs module)   port 29334
#
# Instagram is hand-written because nixpkgs packages only `cmd/mautrix-meta`
# from the shared `mautrix/meta` repository. The unit below is deliberately a
# copy of the shape of the mautrix-meta module (registration oneshot + main
# unit, tokens minted on the host and synced into the live config) with the
# s/MemoryDenyWriteExecute/…/ and postgres ordering differences called out.
#
# Reliability choices common to all three, all overrides of module defaults:
#   * `Restart = "always"` — a bridge that exits cleanly is still a bridge that
#     should come back; `on-failure` would leave it dead until someone notices.
#   * `requires`/`after` on postgresql.target and matrix-secrets — nixpkgs never
#     wires this for the bridges (only its own meta/postgres test does it by
#     hand), and Synapse's `hasLocalPostgresDB` heuristic misses a unix socket.
#   * `homeserver.address` pinned to Synapse's real listener: the modules default
#     to `http://localhost:8448`, which is not where nixpkgs' Synapse listens.
#   * `appservice.address` pinned explicitly, because Synapse has to be able to
#     push transactions to the bridge (Beeper's configs can leave it null).
{ config, lib, pkgs, ... }:

let
  cfg = config.services.matrixStack;
  inherit (cfg) bridges;

  homeserverAddress = "http://${cfg.listenAddress}:${toString cfg.listenPort}";

  # One shape for all three bridges. `database`, `appservicePort` and
  # `environmentFile` are read-only: they are what postgres peer auth, the
  # watchdog probes and the secret generator key off, so they must not drift.
  bridgeSubmodule =
    bridgeName: database: port:
    { ... }:
    {
      options = {
        enable = lib.mkEnableOption "${bridgeName} bridge";

        settings = lib.mkOption {
          type = lib.types.json;
          default = { };
          example = { bridge.private_chat_portal_meta = true; };
          description = ''
            Bridge settings, merged over the stack defaults (homeserver address,
            appservice address, permissions, postgres, encryption).
          '';
        };

        database = lib.mkOption {
          type = lib.types.str;
          readOnly = true;
          default = database;
          description = "PostgreSQL database, role, systemd user and state directory of this bridge.";
        };

        appservicePort = lib.mkOption {
          type = lib.types.port;
          readOnly = true;
          default = port;
          description = "Loopback port the bridge's appservice listener binds.";
        };

        environmentFile = lib.mkOption {
          type = lib.types.path;
          readOnly = true;
          default = "${cfg.secrets.directory}/${database}.env";
          description = "Environment file with the generated pickle/signing keys (see secrets.nix).";
        };

        effectiveSettings = lib.mkOption {
          type = lib.types.json;
          readOnly = true;
          default = bridgeSettings.${bridgeName};
          description = ''
            {option}`settings` merged over the stack defaults — i.e. exactly what
            the bridge's config file is generated from. Exposed for inspection
            (`nix eval ... .bridges.<name>.effectiveSettings`) and for tests.
          '';
        };
      };
    };

  # Token/signing-key material never goes into the store: the store config keeps
  # `$VAR` placeholders and the service's preStart runs envsubst with the
  # environment file generated by ./secrets.nix.
  #
  # `database` is the bridge's own store. bridgev2 bridges (whatsapp, instagram)
  # take it as a *top-level* key; the legacy discord bridge takes it under
  # `appservice`. Both point at the same PostgreSQL database, which peer auth
  # lets us address without a password.
  postgresUri = database: "postgresql://${database}@/${database}?host=/run/postgresql";

  mkCommon =
    { port }:
    {
      homeserver = {
        # `hungry` is Beeper's homeserver and makes the bridge verify it against
        # /versions, exiting fatally on a plain Synapse.
        software = "standard";
        address = homeserverAddress;
        domain = cfg.serverName;
      };
      appservice = {
        hostname = cfg.listenAddress;
        address = "http://${cfg.listenAddress}:${toString port}";
      };
      bridge.permissions = {
        # Levels are block < relay < commands < user < admin; `admin` is `user`
        # plus the admin-only commands, and a full MXID beats a domain beats `*`.
        ${cfg.ownerUserId} = "admin";
        # Everyone else on this tailnet-only homeserver may relay, never log in
        # as someone else. Matches the module default and Beeper's own configs.
        "*" = "relay";
      };
    };

  # bridgev2 (whatsapp, instagram): top-level database block, pickle key pinned
  # from the environment file because the upstream default `generate` is
  # re-rolled on every start of a Nix-generated config — which upstream
  # documents as "the database will have to be reset".
  mkBridgev2Settings =
    {
      database,
      port,
      pickleKeyVar,
    }:
    let
      # `MAUTRIX_<X>_` prefix, e.g. MAUTRIX_WHATSAPP_ENCRYPTION_PICKLE_KEY
      prefix = lib.removeSuffix "_ENCRYPTION_PICKLE_KEY" pickleKeyVar;
    in
    lib.recursiveUpdate (mkCommon { inherit port; }) {
      database = {
        type = "postgres";
        uri = postgresUri database;
      };
      encryption = {
        allow = true;
        default = true;
        require = false;
        pickle_key = "\$${pickleKeyVar}";
      };
      # Durability, not throughput. Upstream's default (64) is an *in-memory*
      # per-portal buffer: the bridge acks the network as soon as the event is
      # enqueued, so anything still buffered when the homeserver is unreachable
      # past mautrix-go's retry budget (~5 attempts, ~60s) is dropped — no row,
      # no retry, nothing to replay. 0 handles events synchronously, so the
      # network's ack waits for the Matrix send and an event that never landed
      # is re-sent by the network instead of vanishing.
      # Cost: serial handling per portal, and a slow homeserver delays the
      # network's ack path (which the network answers with re-delivery, so the
      # failure mode is a duplicate, not a hole).
      portal_event_buffer = 0;
      # These three defaults are `generate` upstream, which for a config file
      # that Nix rewrites on every start means "new value every restart". Pin
      # them with the same generated material; the features stay optional.
      provisioning.shared_secret = "\$${prefix}_PROVISIONING_SHARED_SECRET";
      public_media.signing_key = "\$${prefix}_PUBLIC_MEDIA_SIGNING_KEY";
      direct_media.server_key = "\$${prefix}_DIRECT_MEDIA_SERVER_KEY";
    };

  # Legacy architecture (discord): appservice-nested database, no pickle key at
  # all (the bridge hardcodes its crypto pickle key in the binary), and the
  # encryption block nests under `bridge` — a top-level `encryption` is an
  # unknown key that mautrix-discord silently ignores, which would leave the
  # bridge unencrypted while the other two are encrypted.
  mkLegacySettings =
    { database, port }:
    lib.recursiveUpdate (mkCommon { inherit port; }) {
      appservice.database = {
        type = "postgres";
        uri = postgresUri database;
      };
      bridge.encryption = {
        allow = true;
        default = true;
        require = false;
      };
    };

  bridgeSettings = {
    whatsapp = lib.recursiveUpdate (mkBridgev2Settings {
      database = bridges.whatsapp.database;
      port = bridges.whatsapp.appservicePort;
      pickleKeyVar = "MAUTRIX_WHATSAPP_ENCRYPTION_PICKLE_KEY";
    }) bridges.whatsapp.settings;

    instagram = lib.recursiveUpdate (mkBridgev2Settings {
      database = bridges.instagram.database;
      port = bridges.instagram.appservicePort;
      pickleKeyVar = "MAUTRIX_INSTAGRAM_ENCRYPTION_PICKLE_KEY";
    }) bridges.instagram.settings;

    discord = lib.recursiveUpdate (mkLegacySettings {
      database = bridges.discord.database;
      port = bridges.discord.appservicePort;
    }) bridges.discord.settings;
  };

  # --- Instagram: the bridge nixpkgs has no module (or package) for ----------
  # Same repository and tag as pkgs.mautrix-meta, second command.
  mautrixInstagram = pkgs.mautrix-meta.overrideAttrs (old: {
    pname = "mautrix-instagram";
    subPackages = [ "cmd/mautrix-instagram" ];
    meta = (old.meta or { }) // {
      description = "Matrix-Instagram puppeting bridge";
      mainProgram = "mautrix-instagram";
    };
  });

  instagramStateDir = "/var/lib/${bridges.instagram.database}";
  instagramStoreConfig = (pkgs.formats.yaml { }).generate "mautrix-instagram-config.yaml"
    bridgeSettings.instagram;
  instagramLiveConfig = "${instagramStateDir}/config.yaml";
  instagramRegistration = "${instagramStateDir}/instagram-registration.yaml";

  # The whatsapp module mints its registration file inside the *bridge's*
  # preStart while Synapse is ordered to start before the bridge — on a fresh
  # host Synapse therefore fails to load a registration file that does not exist
  # yet, and nothing restarts it. This oneshot generates the same file *before*
  # Synapse, so first boot works unattended. The bridge's own preStart then finds
  # the file, keeps the tokens and syncs them into its config.
  whatsappStateDir = "/var/lib/${bridges.whatsapp.database}";
  whatsappStoreConfig = (pkgs.formats.json { }).generate "mautrix-whatsapp-config-unsubstituted.json"
    bridgeSettings.whatsapp;
  whatsappLiveConfig = "${whatsappStateDir}/config.yaml";
  whatsappRegistration = "${whatsappStateDir}/whatsapp-registration.yaml";

  # Applies to every bridge unit; `mkForce` because the modules ship
  # `on-failure`, and the ordering because they ship none.
  hardenUnit = {
    wants = [
      "postgresql.target"
      "matrix-secrets.service"
    ];
    after = [
      "postgresql.target"
      "matrix-secrets.service"
    ];
    serviceConfig = {
      Restart = lib.mkForce "always";
      RestartSec = lib.mkForce "15s";
    };
  };
in
{
  options.services.matrixStack.bridges = {
    whatsapp = lib.mkOption {
      type = lib.types.submodule (bridgeSubmodule "whatsapp" "mautrix-whatsapp" 29318);
      default = { };
      description = "Matrix <-> WhatsApp puppeting bridge (mautrix).";
    };
    instagram = lib.mkOption {
      type = lib.types.submodule (bridgeSubmodule "instagram" "mautrix-instagram" 29320);
      default = { };
      description = "Matrix <-> Instagram puppeting bridge (mautrix-instagram).";
    };
    discord = lib.mkOption {
      type = lib.types.submodule (bridgeSubmodule "discord" "mautrix-discord" 29334);
      default = { };
      description = "Matrix <-> Discord puppeting bridge (mautrix-discord).";
    };
  };

  config = lib.mkIf cfg.enable {
    # ---------------- WhatsApp ----------------
    services.mautrix-whatsapp = lib.mkIf bridges.whatsapp.enable {
      enable = true;
      environmentFile = bridges.whatsapp.environmentFile;
      settings = bridgeSettings.whatsapp;
    };

    systemd.services.mautrix-whatsapp-registration = lib.mkIf bridges.whatsapp.enable {
      description = "Generate the mautrix-whatsapp appservice registration (before Synapse)";
      wantedBy = [ "multi-user.target" ];
      before = [
        "matrix-synapse.service"
        "mautrix-whatsapp.service"
      ];
      wants = [ "matrix-secrets.service" ];
      after = [ "matrix-secrets.service" ];
      path = [
        pkgs.envsubst
        pkgs.mautrix-whatsapp
      ];
      restartTriggers = [ whatsappStoreConfig ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        User = "mautrix-whatsapp";
        Group = "mautrix-whatsapp";
        UMask = "0027";
        StateDirectory = bridges.whatsapp.database;
        WorkingDirectory = whatsappStateDir;
        EnvironmentFile = bridges.whatsapp.environmentFile;
        ReadWritePaths = [ whatsappStateDir ];
        ProtectSystem = "strict";
        ProtectHome = true;
        SystemCallFilter = [ "@system-service" ];
      };
      script = ''
        set -eu
        config=${whatsappLiveConfig}
        registration=${whatsappRegistration}

        rm -f "$config"
        envsubst -o "$config" -i ${whatsappStoreConfig}

        if [ ! -f "$registration" ]; then
          mautrix-whatsapp --generate-registration --config="$config" --registration="$registration"
        fi
        chmod 0640 "$registration"
      '';
    };

    # ---------------- Discord -----------------
    # No environmentFile: the legacy discord config has no pickle/signing keys
    # to pin, so there is nothing to substitute and nothing to generate.
    services.mautrix-discord = lib.mkIf bridges.discord.enable {
      enable = true;
      settings = bridgeSettings.discord;
    };

    # ---------------- Instagram ---------------
    users.users.mautrix-instagram = lib.mkIf bridges.instagram.enable {
      isSystemUser = true;
      group = "mautrix-instagram";
      home = instagramStateDir;
      description = "mautrix-instagram bridge user";
    };
    users.groups.mautrix-instagram = lib.mkIf bridges.instagram.enable { };

    systemd.services.mautrix-instagram-registration = lib.mkIf bridges.instagram.enable {
      description = "Generate the mautrix-instagram appservice registration";
      wantedBy = [ "multi-user.target" ];
      before = [ "matrix-synapse.service" ];
      wants = [ "matrix-secrets.service" ];
      after = [ "matrix-secrets.service" ];
      path = [
        pkgs.yq
        pkgs.envsubst
        mautrixInstagram
      ];
      restartTriggers = [ instagramStoreConfig ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        User = "mautrix-instagram";
        Group = "mautrix-instagram";
        UMask = "0027";
        StateDirectory = bridges.instagram.database;
        WorkingDirectory = instagramStateDir;
        EnvironmentFile = bridges.instagram.environmentFile;
        ReadWritePaths = [ instagramStateDir ];
        ProtectSystem = "strict";
        ProtectHome = true;
        SystemCallFilter = [ "@system-service" ];
      };
      # Mirrors nixpkgs' mautrix-meta module: render the config from the store,
      # keep existing tokens, mint a pair if there is none, then make config and
      # registration agree. Tokens therefore survive a rebuild and a restore.
      script = ''
        set -eu
        config=${instagramLiveConfig}
        registration=${instagramRegistration}

        rm -f "$config"
        envsubst -o "$config" -i ${instagramStoreConfig}

        config_has_tokens=$(yq '.appservice | has("as_token") and has("hs_token")' "$config")
        registration_exists=$([ -f "$registration" ] && echo true || echo false)

        if [ "$config_has_tokens" = false ] && [ "$registration_exists" = true ]; then
          yq -sY '.[0].appservice.as_token = .[1].as_token | .[0].appservice.hs_token = .[1].hs_token | .[0]' \
            "$config" "$registration" > "$config.tmp"
          mv "$config.tmp" "$config"
        fi

        cp "$config" "$config.tmp"
        mautrix-instagram --generate-registration --config="$config.tmp" --registration="$registration"
        rm -f "$config.tmp"

        if [ "$config_has_tokens" = false ] && [ "$registration_exists" = false ]; then
          yq -sY '.[0].appservice.as_token = .[1].as_token | .[0].appservice.hs_token = .[1].hs_token | .[0]' \
            "$config" "$registration" > "$config.tmp"
          mv "$config.tmp" "$config"
        fi

        if [ "$config_has_tokens" = true ] || [ "$registration_exists" = true ]; then
          yq -sY '.[1].as_token = .[0].appservice.as_token | .[1].hs_token = .[0].appservice.hs_token | .[1]' \
            "$config" "$registration" > "$registration.tmp"
          mv "$registration.tmp" "$registration"
        fi

        chmod 0640 "$registration"
        rm -f "$config.tmp"
      '';
    };

    systemd.services.mautrix-instagram = lib.mkIf bridges.instagram.enable {
      description = "mautrix-instagram, a Matrix-Instagram puppeting bridge";
      wantedBy = [ "multi-user.target" ];
      wants = [
        "network-online.target"
        "mautrix-instagram-registration.service"
      ] ++ hardenUnit.wants;
      after = [
        "network-online.target"
        "mautrix-instagram-registration.service"
      ] ++ hardenUnit.after;
      path = [ pkgs.ffmpeg-headless ]; # voice messages
      restartTriggers = [ instagramStoreConfig ];
      serviceConfig = {
        Type = "simple";
        User = "mautrix-instagram";
        Group = "mautrix-instagram";
        StateDirectory = bridges.instagram.database;
        WorkingDirectory = instagramStateDir;
        EnvironmentFile = bridges.instagram.environmentFile;
        # Tokens are synced into the live config by the registration unit, which
        # is why this needs no --registration flag (same as the meta module).
        ExecStart = "${lib.getExe mautrixInstagram} --config=${instagramLiveConfig}";
        UMask = "0027";
        LockPersonality = true;
        NoNewPrivileges = true;
        PrivateDevices = true;
        PrivateTmp = true;
        PrivateUsers = true;
        ProtectClock = true;
        ProtectControlGroups = true;
        ProtectHome = true;
        ProtectHostname = true;
        ProtectKernelLogs = true;
        ProtectKernelModules = true;
        ProtectKernelTunables = true;
        ProtectSystem = "strict";
        ReadWritePaths = [ instagramStateDir ];
        RestrictRealtime = true;
        RestrictSUIDSGID = true;
        SystemCallArchitectures = "native";
        SystemCallErrorNumber = "EPERM";
        SystemCallFilter = [ "@system-service" ];
        # Deliberately NOT set: `MemoryDenyWriteExecute`, which upstream's own
        # systemd docs mark as breaking libolm/libsignal.
      } // hardenUnit.serviceConfig;
    };

    # ---------------- Synapse integration -----
    # Synapse loads every appservice registration file at startup and fails hard
    # if one is missing, so it has to start *after* each unit that writes one.
    services.matrix-synapse = lib.mkIf bridges.instagram.enable {
      settings.app_service_config_files = [ instagramRegistration ];
    };

    systemd.services.matrix-synapse = lib.mkMerge [
      (lib.mkIf bridges.whatsapp.enable {
        wants = [ "mautrix-whatsapp-registration.service" ];
        after = [ "mautrix-whatsapp-registration.service" ];
      })
      (lib.mkIf bridges.instagram.enable {
        serviceConfig.SupplementaryGroups = [ "mautrix-instagram" ];
        wants = [ "mautrix-instagram-registration.service" ];
        after = [ "mautrix-instagram-registration.service" ];
      })
    ];

    # ---------------- shared overrides --------
    systemd.services.mautrix-whatsapp = lib.mkIf bridges.whatsapp.enable hardenUnit;

    systemd.services.mautrix-discord = lib.mkIf bridges.discord.enable hardenUnit;

    # The registration oneshot mints the as/hs tokens; it must not race the
    # secret generator either.
    systemd.services.mautrix-discord-registration = lib.mkIf bridges.discord.enable {
      wants = [ "matrix-secrets.service" ];
      after = [ "matrix-secrets.service" ];
    };
  };
}
