# Self-hosted Matrix stack — Synapse + mautrix bridges (Beeper replacement).
# Design + rationale: ~/nix-migration/10-matrix-on-warden.md
#
# Reliability rules encoded here (see the doc for the evidence behind each):
#   * nothing secret ever lands in /nix/store — tokens are minted on the host,
#     shared secrets and pickle keys are generated by ./secrets.nix into /var/lib
#   * postgres over the unix socket with peer auth (no passwords to rotate)
#   * every bridge gets explicit `Restart=always`, postgres ordering and a
#     health probe (./watchdog.nix); dumps + restic for restore (./backup.nix)
{ config, lib, pkgs, ... }:

let
  cfg = config.services.matrixStack;

  # Names are fixed by convention and computed in one place: postgres role name
  # == database name == systemd service user == state directory basename. Peer
  # auth over the unix socket (homeserver.nix) depends on that identity, and so
  # do the backup paths (backup.nix).
  enabledBridges = lib.filter (n: cfg.bridges.${n}.enable) [ "whatsapp" "instagram" "discord" ];
  bridgeDatabases = map (n: cfg.bridges.${n}.database) enabledBridges;

  # whatsapp/instagram hardcode /var/lib/<bridge> in their modules; discord
  # exposes `dataDir`, so read it instead of restating the path.
  bridgeStateDirs =
    lib.optional cfg.bridges.whatsapp.enable "/var/lib/${cfg.bridges.whatsapp.database}"
    ++ lib.optional cfg.bridges.instagram.enable "/var/lib/${cfg.bridges.instagram.database}"
    ++ lib.optional cfg.bridges.discord.enable config.services.mautrix-discord.dataDir;
in
{
  imports = [
    ./secrets.nix
    ./homeserver.nix
    ./bridges.nix
    ./ingress.nix
    ./watchdog.nix
    ./backup.nix
  ];

  options.services.matrixStack = {
    enable = lib.mkEnableOption "the self-hosted Matrix stack (Synapse + mautrix bridges)";

    serverName = lib.mkOption {
      type = lib.types.str;
      example = "warden.tailnet-abc.ts.net";
      description = ''
        Matrix `server_name`. It is baked into every user id, room id and access
        token, so changing it after the homeserver has been used breaks the
        deployment. With tailnet-only ingress (the default) this is the node's
        MagicDNS name, which is also what `tailscale serve` gets a certificate
        for, so no `.well-known` delegation is needed.
      '';
    };

    clientUrl = lib.mkOption {
      type = lib.types.str;
      default = "https://${cfg.serverName}";
      defaultText = lib.literalExpression ''"https://" + config.services.matrixStack.serverName'';
      description = ''
        URL clients log in with (Synapse `public_baseurl`). Defaults to the
        `tailscale serve` HTTPS endpoint on `serverName`.
      '';
    };

    owner = lib.mkOption {
      type = lib.types.str;
      default = "wyli";
      description = "Local account name that is granted admin on every bridge.";
    };

    ownerUserId = lib.mkOption {
      type = lib.types.str;
      readOnly = true;
      default = "@${cfg.owner}:${cfg.serverName}";
      description = "Full Matrix user id of {option}`owner` on this homeserver.";
    };

    databases = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      readOnly = true;
      default = [ "matrix-synapse" ] ++ bridgeDatabases;
      description = ''
        Databases the stack owns: one for Synapse plus one per enabled bridge.
        Each is created by NixOS with a role of the same name as its owner.
      '';
    };

    stateDirectories = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      readOnly = true;
      default = [ "/var/lib/matrix-synapse" ] ++ bridgeStateDirs;
      description = "On-disk state of every service of the stack — what backup.nix snapshots.";
    };

    listenAddress = lib.mkOption {
      type = lib.types.str;
      default = "127.0.0.1";
      description = ''
        Interface Synapse and every bridge listen on. Loopback only by default:
        clients reach the stack through `tailscale serve`, never directly.
      '';
    };

    listenPort = lib.mkOption {
      type = lib.types.port;
      default = 8008;
      description = "Synapse client (and federation) API port on {option}`listenAddress`.";
    };

    watchdog = {
      enable = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Run the periodic health check (see {file}`watchdog.nix`).";
      };
      interval = lib.mkOption {
        type = lib.types.str;
        default = "5min";
        description = "Delay between health checks. A systemd time span.";
      };

      alertRoom = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        example = "!AbCdEfGh:warden.tailnet-abc.ts.net";
        description = ''
          Room id that health failures are posted to. Needs an access token in
          {option}`alertTokenFile`; without it failures are only journaled.
        '';
      };

      alertTokenFile = lib.mkOption {
        type = lib.types.path;
        default = "${config.services.matrixStack.secrets.directory}/alert-token";
        defaultText = lib.literalExpression ''"''${config.services.matrixStack.secrets.directory}/alert-token"'';
        description = "Root-readable file holding the access token used to post alerts.";
      };
    };

    backup = {
      enable = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Nightly logical dumps + restic snapshot of all Matrix state.";
      };

      startAt = lib.mkOption {
        type = lib.types.str;
        default = "02:30";
        description = "systemd calendar spec for the nightly `pg_dump` run.";
      };

      dumpDirectory = lib.mkOption {
        type = lib.types.path;
        default = "/var/backup/postgresql";
        description = ''
          Where the nightly `pg_dump` files are written. restic snapshots this
          directory, and the health check fails when nothing fresh appears in it.
        '';
      };

      repository = lib.mkOption {
        type = lib.types.str;
        default = "file:///var/backup/restic/matrix";
        description = ''
          restic repository URL. Local by default; point this at another host
          over the tailnet (`sftp://...`) or an object store when the
          distributed backup system lands — nothing else has to change.
        '';
      };

      pruneOpts = lib.mkOption {
        type = lib.types.listOf lib.types.str;
        default = [ "--keep-daily 7" "--keep-weekly 4" "--keep-monthly 6" ];
        description = "restic `forget` options applied after every backup.";
      };
    };
  };

  config = lib.mkIf cfg.enable {
    assertions = [
      {
        assertion = lib.hasInfix "." cfg.serverName && !(lib.hasInfix "/" cfg.serverName);
        message = ''
          services.matrixStack.serverName must be a dotted domain (e.g.
          "warden.tailnet-abc.ts.net") — it is used as the Matrix server_name
          and as the `tailscale serve` certificate name.
        '';
      }
      {
        assertion = cfg.owner != "";
        message = "services.matrixStack.owner must not be empty; it becomes the bridge admin user.";
      }
    ];

    # End-to-bridge encryption in every Go bridge goes through libolm, which
    # nixpkgs flags insecure because upstream is unmaintained. The alternative
    # (`withGoolm = true` on the bridge packages) is explicitly *not*
    # recommended by the mautrix developers, so permit it explicitly instead of
    # silently dropping encryption.
    #
    # Not computed from `pkgs.olm`: reading that attribute here would be
    # circular (the package set is built from this very config). When a nixpkgs
    # bump changes the version, the "Refusing to evaluate package '<name>'"
    # error names the exact string to put here.
    nixpkgs.config.permittedInsecurePackages = [ "olm-3.2.16" ];

    # Fixed uids for every service that owns state. restic restores numeric
    # ownership, so without pinned ids a fresh host can hand the bridges
    # different uids and the restored /var/lib/mautrix-* is unreadable. Static
    # ids also remove the dependency on /var/lib/nixos/uid-map after a restore.
    # (Synapse needs no pinning: nixpkgs gives it the static id 224.)
    users.users.mautrix-whatsapp.uid = lib.mkIf cfg.bridges.whatsapp.enable (lib.mkDefault 3002);
    users.users.mautrix-instagram.uid = lib.mkIf cfg.bridges.instagram.enable (lib.mkDefault 3003);
    users.users.mautrix-discord.uid = lib.mkIf cfg.bridges.discord.enable (lib.mkDefault 3004);

    # Federation is not configured at all: the client API is published to the
    # tailnet only (./ingress.nix) and Synapse binds to loopback, so no other
    # homeserver can reach us. Nothing in this stack opens a firewall port —
    # `tailscale serve` proxies from tailscaled to 127.0.0.1. If public
    # federation is ever wanted, that is a vhost + `.well-known` job.
  };
}
