# Matrix stack secrets — generated once on the host, never stored in Nix.
#
# Why not sops-nix (plan 03 step 6) here: none of these values come from outside
# the machine. They are the moral equivalent of Synapse's `homeserver.signing.key`
# — random material the software needs to keep stable across restarts, and
# exactly what the nixpkgs mautrix modules already do for the appservice tokens
# (minted into /var/lib by `--generate-registration`). Keeping them host-local
# means: no key distribution, no decrypt step, and restic backs them up with
# everything else, so a restored host comes back bit-identical.
# `.env`-style API keys that DO come from outside stay on the sops-nix path.
{ config, lib, pkgs, ... }:

let
  cfg = config.services.matrixStack;
  inherit (cfg) bridges;

  # Every bridge gets one environment file; systemd reads it as root before
  # dropping privileges and the module's preStart envsubst substitutes the
  # values into config.yaml, so the placeholders in nix land in the store but
  # the values never do.
  bridgeServices = lib.optionals bridges.whatsapp.enable [ "mautrix-whatsapp.service" ]
    ++ lib.optionals bridges.instagram.enable [ "mautrix-instagram.service" "mautrix-instagram-registration.service" ]
    ++ lib.optionals bridges.discord.enable [ "mautrix-discord.service" "mautrix-discord-registration.service" ];
in
{
  options.services.matrixStack.secrets = {
    directory = lib.mkOption {
      type = lib.types.path;
      default = "/var/lib/matrix-secrets";
      description = "Root-only directory holding every generated secret of the stack.";
    };
  };

  config = lib.mkIf cfg.enable {
    systemd.services.matrix-secrets = {
      description = "Generate and persist Matrix stack secrets (Nix store stays clean)";
      wantedBy = [ "multi-user.target" ];
      before = [ "matrix-synapse.service" ] ++ bridgeServices;
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        UMask = "0077";
        StateDirectory = baseNameOf cfg.secrets.directory;
        # 0750, not 0700: the file itself is 0640 root:matrix-synapse, but a
        # directory without group *search* permission would still give Synapse
        # EACCES when it opens its extra config file. The bridge env files stay
        # 0600 root — systemd (PID 1) reads those, not the services.
        StateDirectoryMode = "0750";
      };
      script = ''
        set -eu
        d=${cfg.secrets.directory}
        rand() { ${pkgs.openssl}/bin/openssl rand -hex 32; }

        # --- Synapse: secrets it must keep stable across restarts -------------
        # Extra config file, read after the store config, so nothing has to be
        # inlined into services.matrix-synapse.settings (which is world-readable
        # in /nix/store). Readable by the matrix-synapse group only.
        if [ ! -f "$d/synapse-secrets.yaml" ]; then
          umask 0027
          tmp="$d/.synapse-secrets.yaml.$$"
          cat > "$tmp" <<EOF
        # Generated by matrix-secrets.service — do not edit, do not commit.
        macaroon_secret_key: "$(rand)"
        registration_shared_secret: "$(rand)"
        form_secret: "$(rand)"
        EOF
          chgrp matrix-synapse "$tmp" 2>/dev/null || true
          chmod 0640 "$tmp"
          mv "$tmp" "$d/synapse-secrets.yaml"
        fi

        # --- bridge environment files ----------------------------------------
        # Names are per bridge because each unit reads its own file.
        bridge_env() {
          name="$1"; prefix="$2"
          [ -f "$d/$name.env" ] && return 0
          tmp="$d/.$name.env.$$"
          umask 0077
          cat > "$tmp" <<EOF
        # Generated by matrix-secrets.service — do not edit, do not commit.
        # Stability matters: a fresh pickle key loses the bridge's existing
        # encryption state, a fresh signing key invalidates previously
        # handed-out media URLs.
        ''${prefix}_ENCRYPTION_PICKLE_KEY=$(rand)
        ''${prefix}_PROVISIONING_SHARED_SECRET=$(rand)
        ''${prefix}_PUBLIC_MEDIA_SIGNING_KEY=$(rand)
        ''${prefix}_DIRECT_MEDIA_SERVER_KEY=$(rand)
        EOF
          chmod 0600 "$tmp"
          mv "$tmp" "$d/$name.env"
        }

        ${lib.optionalString bridges.whatsapp.enable ''bridge_env mautrix-whatsapp MAUTRIX_WHATSAPP''}
        ${lib.optionalString bridges.instagram.enable ''bridge_env mautrix-instagram MAUTRIX_INSTAGRAM''}
        # Discord is deliberately absent: the legacy bridge pins no pickle or
        # signing key through the config, so it has no environment file.

        # --- restic repository password --------------------------------------
        if [ ! -f "$d/restic-password" ]; then
          umask 0077
          rand > "$d/restic-password.tmp"
          mv "$d/restic-password.tmp" "$d/restic-password"
        fi

        # The directory has to be traversable by the matrix-synapse group for
        # Synapse to read its extra config file (see homeserver.nix).
        chgrp matrix-synapse "$d" 2>/dev/null || true
        chmod 0750 "$d"
        chmod 0600 "$d"/*.env "$d/restic-password" 2>/dev/null || true
        chmod 0640 "$d/synapse-secrets.yaml" 2>/dev/null || true
      '';
    };
  };
}
